# Generated by Django 3.1.6 on 2021-02-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Camera_Name', models.CharField(max_length=100)),
                ('Camera_Brand', models.CharField(max_length=100)),
                ('Camera_Details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Camerachoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cameraname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CameraSurvelliance',
            fields=[
                ('Loc_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Camera_ID', models.IntegerField()),
                ('Install_on', models.CharField(max_length=100)),
                ('StreamServer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loc_Name', models.CharField(max_length=100)),
                ('Loc_Address', models.CharField(max_length=100)),
                ('Loc_Survelliance', models.CharField(max_length=10)),
                ('Loc_Area', models.CharField(max_length=100)),
            ],
        ),
    ]
